module.exports = {
  "id": "tok_AdiGcdgmAdW6TS",
  "object": "token",
  "card": {
    "id": "card_AdiGSEz4JSxus8",
    "object": "card",
    "address_city": "Hanalei",
    "address_country": "United States",
    "address_line1": "PO Box 111",
    "address_line1_check": "pass",
    "address_line2": null,
    "address_state": "HI",
    "address_zip": "96714",
    "address_zip_check": "pass",
    "brand": "Visa",
    "country": "US",
    "cvc_check": "pass",
    "dynamic_last4": null,
    "exp_month": 12,
    "exp_year": 2022,
    "funding": "credit",
    "last4": "4242",
    "metadata": {},
    "name": "Robert Conery",
    "tokenization_method": null
  },
  "client_ip": "24.18.44.121",
  "created": 1494545788,
  "email": "robconery@gmail.com",
  "livemode": false,
  "type": "card",
  "used": false
};